manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: mike1808
      url-base: https://github.com/mike1808
    - name: janpfischer
      url-base: https://github.com/janpfischer
    - name: joelspadin
      url-base: https://github.com/joelspadin
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 9490391e1e4010c83291d437b7f9a71ace244581
      import: app/west.yml
    # - name: zmk-dongle-screen
    #   remote: janpfischer
    #   revision: upgrade-4.1
    - name: prospector-zmk-module
      remote: mike1808
      revision: fix/new-status-screan-zmk-refactor
    - name: zmk-locales
      remote: joelspadin
      revision: main
  self:
    path: config
